# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-TZ7smfT0UNKDAeH0E-UONpRJJ1szCv
"""

ligado = 1

print("Bem vindo a sua calculadora")

while ligado == 1:

  print("Indique o primeiro/basse fator")
  primeiroFator = input(type(10))
  primeiroFator = int(primeiroFator)
  print("Indique o segundo/expoente fator")
  segundoFator = input(type(10))
  segundoFator = int(segundoFator)


  print("Indique a operação desejada")
  print("Operações suportadas: Soma(+) Subtração(-) Multiplicação(*) Divisão(/) Resto(%) Potenciação(**) Radiciação(sqrt)")
  operacao = input()

  if operacao == '+':
        resultado = primeiroFator + segundoFator

  if operacao == '-':
        resultado = primeiroFator - segundoFator

  if operacao == '*':
        resultado = primeiroFator * segundoFator

  if operacao == '/':
        resultado = primeiroFator / segundoFator

  if operacao == '%':
       resultado = primeiroFator % segundoFator

  if operacao == '**':
        resultado = primeiroFator ** segundoFator

  if operacao == 'sqrt':
        resultado = primeiroFator ** (1/segundoFator)

  print(resultado)

  print("Continuar operações?")
  print("Para continuar pressione 1")
  print("Para não continuar pressione 0")
  ligado = input()
  ligado = int(ligado)
  if ligado != 1:
    break